CREATE TABLE qa_raw (
	"GlobalID" TEXT,
	"FirstName" TEXT,
	"LastName" TEXT,
	"RemotePartner" TEXT,
	"Role" TEXT,
	"Team Lead" TEXT,
	"DomesticTeamLead1" TEXT,
	"DomesticTeamLead2" TEXT,
	"Sales Order Number" TEXT,
	"Invoice Number" TEXT, 
	"Error_Type" TEXT,
	"Error Detail" TEXT,
	"Critical Errors" TEXT,
	"Major Errors" TEXT,
	"Minor Errors" TEXT,
	"Feedback Errors" TEXT,
	"Score" INT,
	"Auditor" TEXT,
	"Auditor Comment" TEXT, 
	"DateTimeStamp" DATE,
	"Role_Selection" TEXT, 
	"__PowerAppsId__" TEXT,
	"Start Date" TEXT, 
	"Remote Partner Location" TEXT,
	"Is Agent Team Lead" TEXT,
	"Buffer Resource" TEXT
);
